# Generated by Django 4.0.5 on 2022-11-07 19:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherlogin',
            fields=[
                ('teacherid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('teacherpwd', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 8 characters')])),
                ('isactive', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('cc_of_branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch_detail')),
                ('teach_fri_lec1', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_fri_l1', to='branch.branch_detail')),
                ('teach_fri_lec2', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_fri_l2', to='branch.branch_detail')),
                ('teach_fri_lec3', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_fri_l3', to='branch.branch_detail')),
                ('teach_fri_lec4', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_fri_l4', to='branch.branch_detail')),
                ('teach_fri_lec5', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_fri_l5', to='branch.branch_detail')),
                ('teach_fri_lec6', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_fri_l6', to='branch.branch_detail')),
                ('teach_fri_lec7', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_fri_l7', to='branch.branch_detail')),
                ('teach_fri_lec8', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_fri_l8', to='branch.branch_detail')),
                ('teach_mon_lec1', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_mon_l1', to='branch.branch_detail')),
                ('teach_mon_lec2', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_mon_l2', to='branch.branch_detail')),
                ('teach_mon_lec3', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_mon_l3', to='branch.branch_detail')),
                ('teach_mon_lec4', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_mon_l4', to='branch.branch_detail')),
                ('teach_mon_lec5', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_mon_l5', to='branch.branch_detail')),
                ('teach_mon_lec6', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_mon_l6', to='branch.branch_detail')),
                ('teach_mon_lec7', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_mon_l7', to='branch.branch_detail')),
                ('teach_mon_lec8', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_mon_l8', to='branch.branch_detail')),
                ('teach_sat_lec1', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_sat_l1', to='branch.branch_detail')),
                ('teach_sat_lec2', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_sat_l2', to='branch.branch_detail')),
                ('teach_sat_lec3', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_sat_l3', to='branch.branch_detail')),
                ('teach_sat_lec4', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_sat_l4', to='branch.branch_detail')),
                ('teach_sat_lec5', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_sat_l5', to='branch.branch_detail')),
                ('teach_sat_lec6', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_sat_l6', to='branch.branch_detail')),
                ('teach_sat_lec7', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_sat_l7', to='branch.branch_detail')),
                ('teach_sat_lec8', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_sat_l8', to='branch.branch_detail')),
                ('teach_thurs_lec1', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_thurs_l1', to='branch.branch_detail')),
                ('teach_thurs_lec2', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_thurs_l2', to='branch.branch_detail')),
                ('teach_thurs_lec3', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_thurs_l3', to='branch.branch_detail')),
                ('teach_thurs_lec4', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_thurs_l4', to='branch.branch_detail')),
                ('teach_thurs_lec5', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_thurs_l5', to='branch.branch_detail')),
                ('teach_thurs_lec6', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_thurs_l6', to='branch.branch_detail')),
                ('teach_thurs_lec7', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_thurs_l7', to='branch.branch_detail')),
                ('teach_thurs_lec8', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_thurs_l8', to='branch.branch_detail')),
                ('teach_tues_lec1', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_tues_l1', to='branch.branch_detail')),
                ('teach_tues_lec2', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_tues_l2', to='branch.branch_detail')),
                ('teach_tues_lec3', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_tues_l3', to='branch.branch_detail')),
                ('teach_tues_lec4', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_tues_l4', to='branch.branch_detail')),
                ('teach_tues_lec5', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_tues_l5', to='branch.branch_detail')),
                ('teach_tues_lec6', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_tues_l6', to='branch.branch_detail')),
                ('teach_tues_lec7', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_tues_l7', to='branch.branch_detail')),
                ('teach_tues_lec8', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_tues_l8', to='branch.branch_detail')),
                ('teach_wed_lec1', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_wed_l1', to='branch.branch_detail')),
                ('teach_wed_lec2', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_wed_l2', to='branch.branch_detail')),
                ('teach_wed_lec3', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_wed_l3', to='branch.branch_detail')),
                ('teach_wed_lec4', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_wed_l4', to='branch.branch_detail')),
                ('teach_wed_lec5', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_wed_l5', to='branch.branch_detail')),
                ('teach_wed_lec6', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_wed_l6', to='branch.branch_detail')),
                ('teach_wed_lec7', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_wed_l7', to='branch.branch_detail')),
                ('teach_wed_lec8', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teach_wed_l8', to='branch.branch_detail')),
            ],
            managers=[
                ('teach_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
