# Generated by Django 4.0.5 on 2022-11-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherlogin',
            name='cc_of_branch',
        ),
    ]
