# Generated by Django 4.0.5 on 2022-12-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacherlogin_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherlogin',
            name='department',
        ),
    ]
