# Generated by Django 3.2.13 on 2022-05-29 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20220408_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherlogin',
            name='teacherpwd',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 8 characters')]),
        ),
    ]
