# Generated by Django 4.0.5 on 2022-07-12 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0014_branch_detail_mon_lec1'),
        ('teacher', '0003_alter_teacherlogin_teacherpwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherlogin',
            name='cc_of_branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='branch.branch_detail'),
            preserve_default=False,
        ),
    ]
