# Generated by Django 4.0.5 on 2022-12-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_remove_subjects_nolr1_remove_subjects_nolr2_and_more'),
        ('teacher', '0003_remove_teacherlogin_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherlogin',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.department'),
            preserve_default=False,
        ),
    ]
