# Generated by Django 4.0.5 on 2022-10-01 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0014_branch_detail_mon_lec1'),
        ('teacher', '0004_teacherlogin_cc_of_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherlogin',
            name='cc_of_branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch_detail'),
        ),
        migrations.AlterField(
            model_name='teacherlogin',
            name='isactive',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
