# Generated by Django 4.0.5 on 2022-11-15 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_branch_detail_id_alter_branch_detail_name_and_more'),
        ('teacher', '0004_teacherlogin_teach_fri_lec1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherlogin',
            name='cc_of_branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch_detail'),
        ),
    ]
