# Generated by Django 4.0.5 on 2022-10-01 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teacherlogin_cc_of_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherlogin',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
