# Generated by Django 4.0.5 on 2022-10-01 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_teacherlogin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherlogin',
            name='email',
        ),
    ]
