# Generated by Django 4.0.5 on 2023-01-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_remove_teacherlogin_department_teacherlogin_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherlogin',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacherlogin',
            name='blood_group',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherlogin',
            name='gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
