# Generated by Django 4.0.5 on 2023-03-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_teacherlogin_address_teacherlogin_blood_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherlogin',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacherlogin',
            old_name='teacherpwd',
            new_name='pwd',
        ),
        migrations.AlterField(
            model_name='teacherlogin',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=50),
        ),
    ]
