# Generated by Django 4.0.5 on 2022-10-01 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_teacherlogin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherlogin',
            name='teacherpwd',
            field=models.CharField(editable='False', max_length=15, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 8 characters')]),
        ),
    ]
