# Generated by Django 4.0.5 on 2022-10-01 13:38

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_alter_teacherlogin_teacherpwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherlogin',
            name='id',
        ),
        migrations.AddField(
            model_name='teacherlogin',
            name='Name',
            field=models.CharField(default=datetime.datetime(2022, 10, 1, 13, 38, 4, 865133, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherlogin',
            name='teacherid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacherlogin',
            name='teacherpwd',
            field=models.CharField(editable=False, max_length=15, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 8 characters')]),
        ),
    ]
