# Generated by Django 4.0.5 on 2022-10-05 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_remove_teacherlogin_id_teacherlogin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherlogin',
            name='teacherpwd',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 8 characters')]),
        ),
    ]
