# Generated by Django 4.0.5 on 2022-10-14 20:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0016_branch_subjects_subject_teacher'),
        ('teacher', '0011_alter_teacherlogin_teacherpwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_timetable',
            fields=[
                ('teacherlogin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teacher.teacherlogin')),
                ('fri_lec1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri_l1', to='branch.branch_detail')),
                ('fri_lec2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri_l2', to='branch.branch_detail')),
                ('fri_lec3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri_l3', to='branch.branch_detail')),
                ('fri_lec4', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri_l4', to='branch.branch_detail')),
                ('fri_lec5', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri_l5', to='branch.branch_detail')),
                ('fri_lec6', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri_l6', to='branch.branch_detail')),
                ('fri_lec7', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri_l7', to='branch.branch_detail')),
                ('fri_lec8', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri_l8', to='branch.branch_detail')),
                ('mon_lec1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_l1', to='branch.branch_detail')),
                ('mon_lec2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_l2', to='branch.branch_detail')),
                ('mon_lec3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_l3', to='branch.branch_detail')),
                ('mon_lec4', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_l4', to='branch.branch_detail')),
                ('mon_lec5', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_l5', to='branch.branch_detail')),
                ('mon_lec6', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_l6', to='branch.branch_detail')),
                ('mon_lec7', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_l7', to='branch.branch_detail')),
                ('mon_lec8', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_l8', to='branch.branch_detail')),
                ('sat_lec1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat_l1', to='branch.branch_detail')),
                ('sat_lec2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat_l2', to='branch.branch_detail')),
                ('sat_lec3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat_l3', to='branch.branch_detail')),
                ('sat_lec4', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat_l4', to='branch.branch_detail')),
                ('sat_lec5', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat_l5', to='branch.branch_detail')),
                ('sat_lec6', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat_l6', to='branch.branch_detail')),
                ('sat_lec7', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat_l7', to='branch.branch_detail')),
                ('sat_lec8', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat_l8', to='branch.branch_detail')),
                ('thurs_lec1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thurs_l1', to='branch.branch_detail')),
                ('thurs_lec2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thurs_l2', to='branch.branch_detail')),
                ('thurs_lec3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thurs_l3', to='branch.branch_detail')),
                ('thurs_lec4', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thurs_l4', to='branch.branch_detail')),
                ('thurs_lec5', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thurs_l5', to='branch.branch_detail')),
                ('thurs_lec6', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thurs_l6', to='branch.branch_detail')),
                ('thurs_lec7', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thurs_l7', to='branch.branch_detail')),
                ('thurs_lec8', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thurs_l8', to='branch.branch_detail')),
                ('tues_lec1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tues_l1', to='branch.branch_detail')),
                ('tues_lec2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tues_l2', to='branch.branch_detail')),
                ('tues_lec3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tues_l3', to='branch.branch_detail')),
                ('tues_lec4', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tues_l4', to='branch.branch_detail')),
                ('tues_lec5', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tues_l5', to='branch.branch_detail')),
                ('tues_lec6', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tues_l6', to='branch.branch_detail')),
                ('tues_lec7', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tues_l7', to='branch.branch_detail')),
                ('tues_lec8', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tues_l8', to='branch.branch_detail')),
                ('wed_lec1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed_l1', to='branch.branch_detail')),
                ('wed_lec2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed_l2', to='branch.branch_detail')),
                ('wed_lec3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed_l3', to='branch.branch_detail')),
                ('wed_lec4', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed_l4', to='branch.branch_detail')),
                ('wed_lec5', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed_l5', to='branch.branch_detail')),
                ('wed_lec6', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed_l6', to='branch.branch_detail')),
                ('wed_lec7', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed_l7', to='branch.branch_detail')),
                ('wed_lec8', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed_l8', to='branch.branch_detail')),
            ],
            bases=('teacher.teacherlogin',),
            managers=[
                ('teach_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
