# Generated by Django 4.0.5 on 2022-12-10 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Objective_1', models.CharField(max_length=50)),
                ('Objective_2', models.CharField(max_length=50)),
                ('Objective_3', models.CharField(max_length=50)),
                ('Objective_4', models.CharField(max_length=50)),
                ('Objective_5', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, unique=True)),
                ('Objective_1', models.CharField(max_length=50)),
                ('Objective_2', models.CharField(max_length=50)),
                ('Objective_3', models.CharField(max_length=50)),
                ('Objective_4', models.CharField(max_length=50)),
                ('Objective_5', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.course')),
            ],
            managers=[
                ('sub_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
