# Generated by Django 4.0.5 on 2022-10-14 19:49

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('subject_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            managers=[
                ('sub_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
