# Generated by Django 4.0.5 on 2022-11-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
