# Generated by Django 4.0.5 on 2022-12-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.course'),
            preserve_default=False,
        ),
    ]
