# Generated by Django 4.0.5 on 2022-12-10 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_department_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='course',
        ),
        migrations.AddField(
            model_name='subjects',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.department'),
            preserve_default=False,
        ),
    ]
