# Generated by Django 4.0.5 on 2022-12-10 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_remove_subjects_course_subjects_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='department',
        ),
        migrations.AddField(
            model_name='subjects',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.course'),
            preserve_default=False,
        ),
    ]
