# Generated by Django 4.0.5 on 2022-12-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_remove_subjects_department_subjects_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='NOLR1',
            field=models.IntegerField(default=8, help_text='Number Of Lectures Required'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='NOLR2',
            field=models.IntegerField(default=8, help_text='Number Of Lectures Required'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='NOLR3',
            field=models.IntegerField(default=8, help_text='Number Of Lectures Required'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='NOLR4',
            field=models.IntegerField(default=8, help_text='Number Of Lectures Required'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='NOLR5',
            field=models.IntegerField(default=8, help_text='Number Of Lectures Required'),
        ),
    ]
