# Generated by Django 4.0.5 on 2022-12-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_subjects_nolr1_subjects_nolr2_subjects_nolr3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='NOLT1',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
