# Generated by Django 4.0.5 on 2022-12-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_subjects_nolt1'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='NOLT2',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='subjects',
            name='NOLT3',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='subjects',
            name='NOLT4',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='subjects',
            name='NOLT5',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
