# Generated by Django 4.0.5 on 2022-12-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_subjects_nolt2_subjects_nolt3_subjects_nolt4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='NOLR1',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='NOLR2',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='NOLR3',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='NOLR4',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='NOLR5',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='NOLT1',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='NOLT2',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='NOLT3',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='NOLT4',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='NOLT5',
        ),
    ]
