# Generated by Django 4.0.5 on 2022-12-18 12:13

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_subjects_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('course_obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='department',
            managers=[
                ('department_obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Objective_1',
            new_name='Course_Objective_1',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Objective_2',
            new_name='Course_Objective_2',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Objective_3',
            new_name='Course_Objective_3',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Objective_5',
            new_name='Course_Objective_4',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Objective_4',
            new_name='Course_Objective_5',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='Objective_1',
            new_name='CO_1',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='Objective_2',
            new_name='CO_2',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='Objective_3',
            new_name='CO_3',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='Objective_4',
            new_name='CO_4',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='Objective_5',
            new_name='CO_5',
        ),
    ]
