# Generated by Django 4.0.5 on 2022-12-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_alter_course_managers_alter_department_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='department',
        ),
    ]
