# Generated by Django 4.0.5 on 2022-12-21 09:59

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_delete_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='topics1',
            field=django_jsonfield_backport.models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='topics2',
            field=django_jsonfield_backport.models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='topics3',
            field=django_jsonfield_backport.models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='topics4',
            field=django_jsonfield_backport.models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='topics5',
            field=django_jsonfield_backport.models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
