# Generated by Django 4.0.5 on 2022-12-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_subjects_topics1_subjects_topics2_subjects_topics3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='topics1',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='topics2',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='topics3',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='topics4',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='topics5',
            field=models.JSONField(),
        ),
    ]
