# Generated by Django 4.0.5 on 2022-12-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_alter_subjects_topics1_alter_subjects_topics2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='to1',
            field=models.CharField(default=1, help_text="Enter topics seperated by ','", max_length=500, verbose_name='Topics in Unit 5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjects',
            name='topics1',
            field=models.JSONField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='topics2',
            field=models.JSONField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='topics3',
            field=models.JSONField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='topics4',
            field=models.JSONField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='topics5',
            field=models.JSONField(blank=True, default=None, editable=False, null=True),
        ),
    ]
