# Generated by Django 4.0.5 on 2022-12-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_subjects_to1_alter_subjects_topics1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='to2',
            field=models.CharField(default=1, help_text="Enter topics seperated by ','", max_length=500, verbose_name='Topics in Unit 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='to3',
            field=models.CharField(default=1, help_text="Enter topics seperated by ','", max_length=500, verbose_name='Topics in Unit 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='to4',
            field=models.CharField(default=1, help_text="Enter topics seperated by ','", max_length=500, verbose_name='Topics in Unit 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='to5',
            field=models.CharField(default=1, help_text="Enter topics seperated by ','", max_length=500, verbose_name='Topics in Unit 5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjects',
            name='to1',
            field=models.CharField(help_text="Enter topics seperated by ','", max_length=500, verbose_name='Topics in Unit 1'),
        ),
    ]
