# Generated by Django 4.0.5 on 2023-01-14 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_alter_subjects_to1_alter_subjects_to2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('Ques1_partA', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques1_partB', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques1_partC', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques1_partD', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques1_partE', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques1_partF', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques1_partG', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques1_partH', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques1_partI', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques1_partJ', models.CharField(blank=True, max_length=120, null=True)),
                ('MarksQues1', models.IntegerField()),
                ('Ques2_partA', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques2_partB', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques2_partC', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques2_partD', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques2_partE', models.CharField(blank=True, max_length=120, null=True)),
                ('MarksQues2', models.IntegerField()),
                ('Ques3_partA', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques3_partB', models.CharField(blank=True, max_length=120, null=True)),
                ('MarksQues3', models.IntegerField()),
                ('Ques4_partA', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques4_partB', models.CharField(blank=True, max_length=120, null=True)),
                ('MarksQues4', models.IntegerField()),
                ('Ques5_partA', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques5_partB', models.CharField(blank=True, max_length=120, null=True)),
                ('MarksQues5', models.IntegerField()),
                ('Ques6_partA', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques6_partB', models.CharField(blank=True, max_length=120, null=True)),
                ('MarksQues6', models.IntegerField()),
                ('Ques7_partA', models.CharField(blank=True, max_length=120, null=True)),
                ('Ques7_partB', models.CharField(blank=True, max_length=120, null=True)),
                ('MarksQues7', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.subjects')),
            ],
        ),
    ]
