# Generated by Django 4.0.5 on 2023-01-25 19:39

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_alter_question_paper_ques1_parta_marks_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question_paper',
            managers=[
                ('question_paper_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
