# Generated by Django 4.0.5 on 2023-02-05 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0022_alter_subjects_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuingOrganization', models.CharField(max_length=150, verbose_name='Issuing Organization')),
                ('issuingYear', models.CharField(max_length=4, verbose_name='Issuing Year')),
                ('link', models.CharField(max_length=250, verbose_name='Achievement Link')),
                ('description', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('achieve_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
