# Generated by Django 4.0.5 on 2023-03-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_question_remove_question_paper_marksques1_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question_paper',
            managers=[
            ],
        ),
    ]
