# Generated by Django 4.0.5 on 2023-03-26 18:27

from django.db import migrations, models
import erp.models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_alter_question_paper_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_paper',
            name='Ques13',
            field=models.JSONField(default=erp.models.default_json),
        ),
        migrations.AddField(
            model_name='question_paper',
            name='Ques14',
            field=models.JSONField(default=erp.models.default_json),
        ),
        migrations.AddField(
            model_name='question_paper',
            name='Ques15',
            field=models.JSONField(default=erp.models.default_json),
        ),
    ]
