# Generated by Django 4.0.5 on 2022-11-07 19:55

import django.core.validators
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentlogin',
            fields=[
                ('studentid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=40)),
                ('studentpwd', models.CharField(editable=False, max_length=15, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 50 characters')])),
                ('isactive', models.IntegerField(null=True)),
                ('branch', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60)),
            ],
            managers=[
                ('stud_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
