# Generated by Django 4.0.5 on 2022-12-19 09:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_delete_department'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlogin',
            name='isactive',
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='DOA',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='admissionThrough',
            field=models.CharField(choices=[('DIRECT', 'DIRECT'), ('COUNSELLING', 'COUNSELLING')], default='DIRECT', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='category',
            field=models.CharField(choices=[('GEN', 'GEN'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('OTHERS', 'OTHERS')], default='GEN', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='course',
            field=models.ForeignKey(default='B.Tech', on_delete=django.db.models.deletion.CASCADE, to='erp.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], default='MALE', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='religion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='semester',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
    ]
