# Generated by Django 3.2 on 2022-03-30 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogin',
            name='studentpwd',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 50 characters')]),
        ),
    ]
