# Generated by Django 4.0.5 on 2022-11-15 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_alter_branch_detail_fri_lec1_and_more'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogin',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='branch.branch_detail'),
        ),
    ]
