# Generated by Django 3.2 on 2022-04-08 05:26

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentlogin_studentpwd'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentlogin',
            managers=[
                ('stud_obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='isactive',
            field=models.IntegerField(null=True),
        ),
    ]
