# Generated by Django 4.0.5 on 2022-12-19 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentlogin_adhar_studentlogin_admissionunder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlogin',
            name='session',
            field=models.IntegerField(default=2022, verbose_name=django.core.validators.MaxValueValidator(2022)),
        ),
    ]
