# Generated by Django 4.0.5 on 2022-10-01 19:42

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0014_branch_detail_mon_lec1'),
        ('student', '0003_auto_20220408_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlogin',
            name='id',
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='branch.branch_detail'),
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='email',
            field=models.EmailField(default=datetime.datetime(2022, 10, 1, 19, 42, 33, 759610, tzinfo=utc), max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='student_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentlogin',
            name='studentid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentlogin',
            name='studentpwd',
            field=models.CharField(editable=False, max_length=15, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 50 characters')]),
        ),
    ]
