# Generated by Django 4.0.5 on 2022-10-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_studentlogin_id_studentlogin_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogin',
            name='branch',
            field=models.CharField(max_length=20),
        ),
    ]
