# Generated by Django 4.0.5 on 2022-12-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentlogin_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogin',
            name='fatherIncome',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentlogin',
            name='fatherMobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentlogin',
            name='highSchoolRollNo',
            field=models.IntegerField(verbose_name='10th Roll Number'),
        ),
        migrations.AlterField(
            model_name='studentlogin',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentlogin',
            name='motherIncome',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentlogin',
            name='motherMobile',
            field=models.IntegerField(),
        ),
    ]
