# Generated by Django 4.0.5 on 2022-12-19 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentlogin_fatherincome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlogin',
            name='IntermediateBoard',
            field=models.CharField(default=1, help_text='In Format CBSE/UP', max_length=30, verbose_name='12th Board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='IntermediateMarks',
            field=models.IntegerField(default=1, verbose_name='12th Total Marks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='IntermediateName',
            field=models.CharField(default=1, max_length=30, verbose_name='12th School Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='IntermediatePassingYear',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2020)], verbose_name='12th Passing Year'),
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='IntermediatePercentage',
            field=models.FloatField(default=1, verbose_name='12th percentage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='IntermediateRollNo',
            field=models.IntegerField(default=1, verbose_name='12th Roll Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='PCMpercentage',
            field=models.FloatField(default=1, verbose_name='PCM Percentage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='highSchoolMarks',
            field=models.IntegerField(default=1, verbose_name='10th Total Marks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='highSchoolPassingYear',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2020)], verbose_name='10th Passing Year'),
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='highSchoolPercentage',
            field=models.FloatField(default=1, verbose_name='10th percentage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='hostelName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Hostel Name'),
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='hosteller',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentlogin',
            name='adhar',
            field=models.IntegerField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='Adhar'),
        ),
        migrations.AlterField(
            model_name='studentlogin',
            name='highSchoolBoard',
            field=models.CharField(help_text='In Format CBSE/UP', max_length=30, verbose_name='10th Board'),
        ),
        migrations.AlterField(
            model_name='studentlogin',
            name='highSchoolName',
            field=models.CharField(max_length=30, verbose_name='10th School Name'),
        ),
        migrations.AlterField(
            model_name='studentlogin',
            name='session',
            field=models.IntegerField(default=2022, validators=[django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
