# Generated by Django 4.0.5 on 2023-01-02 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0014_branch_detail_pso_1_branch_detail_pso_2_and_more'),
        ('student', '0011_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branch.branch_detail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
