# Generated by Django 4.0.5 on 2023-01-02 09:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_rename_marks_student_marks'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student_marks',
            managers=[
                ('marks_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
