# Generated by Django 4.0.5 on 2023-01-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_student_marks_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_marks',
            name='pue_marks',
        ),
        migrations.RemoveField(
            model_name='student_marks',
            name='re_pue_marks',
        ),
        migrations.RemoveField(
            model_name='student_marks',
            name='st1_marks',
        ),
        migrations.RemoveField(
            model_name='student_marks',
            name='st2_marks',
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques1_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques1_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques1_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques1_partC_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques1_partD_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques1_partE_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques1_partF_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques1_partG_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques1_partH_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques1_partI_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques1_partJ_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques2_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques2_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques2_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques2_partC_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques2_partD_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques2_partE_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques3_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques3_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques3_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques4_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques4_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques4_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques5_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques5_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques5_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques6_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques6_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques6_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques7_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques7_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_Ques7_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='PUE_total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques1_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques1_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques1_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques1_partC_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques1_partD_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques1_partE_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques1_partF_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques1_partG_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques1_partH_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques1_partI_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques1_partJ_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques2_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques2_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques2_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques2_partC_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques2_partD_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques2_partE_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques3_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques3_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques3_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques4_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques4_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques4_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques5_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques5_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques5_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques6_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques6_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques6_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques7_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques7_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_Ques7_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REPUE_total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques1_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques1_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques1_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques1_partC_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques1_partD_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques1_partE_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques1_partF_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques1_partG_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques1_partH_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques1_partI_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques1_partJ_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques2_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques2_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques2_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques2_partC_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques2_partD_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques2_partE_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques3_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques3_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques3_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques4_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques4_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques4_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques5_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques5_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques5_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques6_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques6_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques6_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques7_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques7_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_Ques7_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='REST_total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques1_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques1_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques1_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques1_partC_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques1_partD_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques1_partE_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques1_partF_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques1_partG_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques1_partH_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques1_partI_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques1_partJ_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques2_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques2_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques2_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques2_partC_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques2_partD_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques2_partE_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques3_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques3_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques3_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques4_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques4_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques4_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques5_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques5_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques5_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques6_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques6_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques6_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques7_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques7_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_Ques7_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST1_total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques1_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques1_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques1_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques1_partC_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques1_partD_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques1_partE_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques1_partF_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques1_partG_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques1_partH_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques1_partI_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques1_partJ_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques2_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques2_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques2_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques2_partC_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques2_partD_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques2_partE_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques3_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques3_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques3_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques4_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques4_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques4_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques5_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques5_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques5_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques6_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques6_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques6_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques7_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques7_partA_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_Ques7_partB_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ST2_total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
