# Generated by Django 4.0.5 on 2023-03-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_studentlogin_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentlogin',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='studentlogin',
            old_name='studentpwd',
            new_name='pwd',
        ),
        migrations.AlterField(
            model_name='studentlogin',
            name='personalEmail',
            field=models.EmailField(max_length=50),
        ),
    ]
