# Generated by Django 4.0.5 on 2023-04-22 14:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0018_branch_subjects_optional_teacher'),
        ('student', '0017_rename_student_name_studentlogin_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='practical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('is_evaulated', models.BooleanField(default=False)),
                ('obtained_marks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_marks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('file', models.FileField(upload_to='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentlogin')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch_subjects')),
            ],
        ),
    ]
