# Generated by Django 4.0.5 on 2022-11-07 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('erp', '0001_initial'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_subjects',
            name='branch_subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erp.subjects'),
        ),
        migrations.AddField(
            model_name='branch_subjects',
            name='subject_teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherlogin'),
        ),
    ]
