# Generated by Django 4.0.5 on 2022-07-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='branch',
            new_name='branch_detail',
        ),
    ]
