# Generated by Django 4.0.5 on 2022-07-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_rename_branch_branch_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lec',
            name='fac',
        ),
        migrations.RemoveField(
            model_name='lec',
            name='loc',
        ),
        migrations.RemoveField(
            model_name='lec',
            name='sub',
        ),
    ]
