# Generated by Django 4.0.5 on 2022-12-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_branch_detail_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_detail',
            name='section',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
    ]
