# Generated by Django 4.0.5 on 2022-11-15 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_subjects_subject_name'),
        ('teacher', '0001_initial'),
        ('branch', '0003_alter_branch_detail_fri_lec1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_detail',
            name='mon_lec1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mon_l1', to='branch.branch_subjects'),
        ),
        migrations.AlterUniqueTogether(
            name='branch_subjects',
            unique_together={('branch_subject', 'subject_teacher')},
        ),
    ]
