# Generated by Django 4.0.5 on 2022-07-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_timetable_delete_lec_alter_branch_detail_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
    ]
