# Generated by Django 4.0.5 on 2022-12-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_alter_branch_subjects_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_detail',
            name='section',
            field=models.CharField(help_text='Caps Only', max_length=1),
        ),
    ]
