# Generated by Django 4.0.5 on 2022-07-12 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_alter_subjects_managers_branch_detail_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch_detail',
            name='subject',
        ),
        migrations.AddField(
            model_name='timetable',
            name='lec1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='l1', to='branch.subjects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='lec2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='l2', to='branch.subjects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='lec3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='l3', to='branch.subjects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='lec4',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='l4', to='branch.subjects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='lec5',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='l5', to='branch.subjects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='lec6',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='l6', to='branch.subjects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='lec7',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='l7', to='branch.subjects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='lec8',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='l8', to='branch.subjects'),
            preserve_default=False,
        ),
    ]
