# Generated by Django 4.0.5 on 2022-12-10 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_remove_subjects_course_subjects_department'),
        ('branch', '0006_alter_branch_detail_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch_detail',
            name='course',
        ),
        migrations.AddField(
            model_name='branch_detail',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.department'),
            preserve_default=False,
        ),
    ]
