# Generated by Django 4.0.5 on 2022-07-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0007_remove_branch_detail_subject_timetable_lec1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='name',
        ),
    ]
