# Generated by Django 4.0.5 on 2022-12-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0007_remove_branch_detail_course_branch_detail_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_subjects',
            name='NOLR1',
            field=models.IntegerField(default=8, help_text='Number Of Lectures Required for Objective'),
        ),
        migrations.AddField(
            model_name='branch_subjects',
            name='NOLR2',
            field=models.IntegerField(default=8, help_text='Number Of Lectures Required'),
        ),
        migrations.AddField(
            model_name='branch_subjects',
            name='NOLR3',
            field=models.IntegerField(default=8, help_text='Number Of Lectures Required'),
        ),
        migrations.AddField(
            model_name='branch_subjects',
            name='NOLR4',
            field=models.IntegerField(default=8, help_text='Number Of Lectures Required'),
        ),
        migrations.AddField(
            model_name='branch_subjects',
            name='NOLR5',
            field=models.IntegerField(default=8, help_text='Number Of Lectures Required'),
        ),
        migrations.AddField(
            model_name='branch_subjects',
            name='NOLT1',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='branch_subjects',
            name='NOLT2',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='branch_subjects',
            name='NOLT3',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='branch_subjects',
            name='NOLT4',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='branch_subjects',
            name='NOLT5',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
