# Generated by Django 4.0.5 on 2022-12-12 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0008_branch_subjects_nolr1_branch_subjects_nolr2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_subjects',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branch.branch_detail'),
            preserve_default=False,
        ),
    ]
