# Generated by Django 4.0.5 on 2022-12-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_subjects_code'),
        ('teacher', '0005_remove_teacherlogin_isactive'),
        ('branch', '0009_branch_subjects_branch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch_subjects',
            unique_together={('branch_subject', 'subject_teacher', 'branch')},
        ),
        migrations.AlterField(
            model_name='branch_subjects',
            name='NOLR1',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='branch_subjects',
            name='NOLR2',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='branch_subjects',
            name='NOLR3',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='branch_subjects',
            name='NOLR4',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='branch_subjects',
            name='NOLR5',
            field=models.IntegerField(default=8),
        ),
    ]
