# Generated by Django 4.0.5 on 2022-07-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0010_alter_branch_detail_fri_lec1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='branch_detail',
        ),
    ]
