# Generated by Django 4.0.5 on 2022-12-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_alter_course_managers_alter_department_managers_and_more'),
        ('branch', '0011_remove_branch_detail_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_detail',
            name='course',
            field=models.ForeignKey(default='B.Tech', on_delete=django.db.models.deletion.CASCADE, to='erp.course'),
            preserve_default=False,
        ),
    ]
