# Generated by Django 4.0.5 on 2022-07-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0012_branch_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch_detail',
            name='mon_lec1',
        ),
    ]
