# Generated by Django 4.0.5 on 2022-12-19 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0012_branch_detail_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_detail',
            name='semester',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
    ]
