# Generated by Django 4.0.5 on 2022-07-12 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0013_remove_branch_detail_mon_lec1'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_detail',
            name='mon_lec1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_l1', to='branch.subjects'),
        ),
    ]
