# Generated by Django 4.0.5 on 2022-12-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0013_branch_detail_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_detail',
            name='PSO_1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch_detail',
            name='PSO_2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch_detail',
            name='PSO_3',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch_detail',
            name='PSO_4',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch_detail',
            name='PSO_5',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
