# Generated by Django 4.0.5 on 2023-01-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0014_branch_detail_pso_1_branch_detail_pso_2_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch_detail',
            unique_together={('name', 'batch', 'section')},
        ),
    ]
