# Generated by Django 4.0.5 on 2023-01-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0015_alter_branch_detail_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_detail',
            name='total_strength',
            field=models.IntegerField(default=70),
        ),
    ]
