# Generated by Django 4.0.5 on 2022-10-14 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_alter_teacherlogin_teacherpwd'),
        ('branch', '0015_branch_subjects_alter_branch_detail_fri_lec1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_subjects',
            name='subject_teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherlogin'),
        ),
    ]
