# Generated by Django 4.0.5 on 2022-10-14 20:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0016_branch_subjects_subject_teacher'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='branch_subjects',
            managers=[
                ('branch_sub_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
