# Generated by Django 4.0.5 on 2023-03-28 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_rename_name_teacherlogin_name_and_more'),
        ('branch', '0017_branch_subjects_lecture_1_branch_subjects_lecture_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_subjects',
            name='optional_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optional_teacher', to='teacher.teacherlogin', verbose_name='Teacher 2'),
        ),
    ]
