# Generated by Django 4.0.5 on 2022-12-10 14:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mark_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('present', models.BooleanField(verbose_name='Present')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentlogin')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.subjects')),
            ],
            managers=[
                ('attend_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
