# Generated by Django 4.0.5 on 2022-11-18 21:31

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_subjects_subject_name'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mark_attendance',
            managers=[
                ('attend_obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='mark_attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.subjects'),
        ),
    ]
