# Generated by Django 4.0.5 on 2022-12-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('attendance', '0002_mark_attendance_lecture_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mark_attendance',
            unique_together={('student', 'date', 'lecture_number')},
        ),
    ]
