# Generated by Django 4.0.5 on 2022-12-20 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_mark_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark_attendance',
            name='semester',
            field=models.IntegerField(default=1, editable=False, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='mark_attendance',
            name='session',
            field=models.IntegerField(default=2022, editable=False, validators=[django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
