# Generated by Django 4.0.5 on 2022-12-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_mark_attendance_semester_mark_attendance_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark_attendance',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='mark_attendance',
            name='session',
        ),
    ]
